# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64c67f2942eab952fd9ca8db13c4ca30cbca14789b62615d989eaaf689ff87acb2cdec1e6c2b36da4fe0fe8a48accf0fc1bdc830351378f8c128896b70ea56c4

test:
  secret_key_base: 19098ab8801b9d5765cfebb61d0b00e6583b04b3c6d255533e7b2b6ec023c63ed77a47b6fd6f67d26e16d1cc4b7dce6b7b527e48f184cc72195ea094e1f36f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
